### ISSUE TITLE
Integrate Repository with Codacy/ CodeClimate 

### ISSUE THREAD

**Issue by OluwmayowaF** [BuildForSDG/Team-083-Frontend#2]

**Comment by OluwmayowaF** [comment]
Blocker from the Andela team, Awaiting Resolution
<img width="1290" alt="Screen Shot 2020-05-04 at 7 56 07 PM" src="https://user-images.githubusercontent.com/54279480/81205504-b0bfab00-8fc2-11ea-8cd4-53776091adc0.png">

**Comment by vicradon** [comment]
Wow, they should resolve it fast so we can move fully into sprint 2
